package br.edu.femass.biblioteca.model;

public enum Nacionalidade {

    AFEGANISTAO("Afeganistão", "afegã(o)","afegão", "afegã"),
    AFRICA_DO_SUL("África do Sul","sul-africano(a)","sul-africano","sul-africana"),
    ALBANIA("Albânia", "albanês(esa)","albanês","albanesa"),
    ALEMANHA("Alemanha","alemã(ão)","alemão","alemã"),
    ANDORRA("Andorra","andorrano(a)","andorrano","andorrana"),
    ANGOLA("Angola","angolano(a)","angolano","angolana"),
    ANGUILA("Anguila", "anguilano(a)","anguilano","anguilana"),
    ANTIGUA("Antígua e Barbuda","antiguano(a)","antiguano","antiguana"),
    ANTILHAS("Antilhas Holandesas","antilhano(a)","antilhano","antilhana"),
    ARABIA_SAUDITA("Arábia Saudita","árabe-saudita","árabe-saudita","árabe-saudita"),
    ARGELIA("Argélia","argelino(a)","argelino","argelina"),
    ARGENTINA("Argentina","argentino(a)","argentino","argentina"),
    ARMENIA("Armênia","arménio(a)","arménio",	"arménia"),
    ARUBA("Aruba","arubano(a)","arubano","arubana"),
    AUSTRALIA("Austrália","australiano(a)","australiano","australiana"),
    AUSTRIA("Áustria","austríaco(a)","austríaco","austríaca"),
    AZERBAIJAO("Azerbaijão","azeri","azeri","azeri"),
    BAHAMAS("Bahamas","baamiano(a)","baamiano","baamiana"),
    BAHREIN("Bahrein","barenita","barenita","barenita"),
    BANGLADESH("Bangladesh","bangladechiano(a)","bangladechiano","bangladechiana"),
    BARBADOS("Barbados","barbadense","barbadense","barbadense"),
    BELGICA("Bélgica","belga","belga","belga"),
    BELIZE("Belize","belizenho(a)","belizenho","belizenha"),
    BENIN("Benim","benineseo(a)","benineseo","beninesea"),
    BERMUDAS("Bermudas","bermudense","bermudense","bermudense"),
    BIELORRUSSIA("Bielorrússia","bielorrusso(a)","bielorrusso","bielorrussa"),
    BOLIVIA("Bolívia","boliviano(a)","boliviano","boliviana"),
    BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina","bósnio(a)","bósnio","bósnia"),
    BOTSWANA("Botswana","botsuano(a)","botsuano","botsuana"),
    BRASIL("Brasil","brasileiro(a)","brasileiro","brasileira"),
    BRUNEI("Brunei","bruneíno(a)","bruneíno","bruneína"),
    BULGARIA("Bulgária","búlgaro(a)","búlgaro","búlgara"),
    BURQUINA("Burquina","Fasso	burquino(a)","burquino","burquina"),
    BURUNDI("Burundi","burundiano(a)","burundiano","burundiana"),
    BUTAO("Butão","butanês(esa)","butanês","butanesa"),
    CABO_VERDE("Cabo Verde","cabo-verdiano(a)","cabo-verdiano","cabo-verdiana"),
    CAMAROES("Camarões","camaronês(esa)","camaronês","camaronesa"),
    CAMBOJA("Camboja","cambojano(a)","cambojano","cambojana"),
    CANADA("Canadá","canadiano(a)","canadiano","canadiana"),
    CATAR("Catar","catariano(a)","catariano","catariana"),
    CAZAQUISTAO("Cazaquistão","cazaque","cazaque","cazaque"),
    CHADE("Chade","chadiano(a)","chadiano","chadiana"),
    CHILE("Chile","chileno(a)","chileno","chilena"),
    CHINA("China","chinês(esa)","chino","china"),
    CHIPRE("Chipre", "cipriota","cipriota","cipriota"),
    COLOMBIA("Colômbia","colombiano(a)","colombiano","colombiana"),
    COMORES("Comores","comoriano(a)","comoriano","comoriana"),
    REPUBLICA_DO_CONGO("República do Congo","congolês(a)","congolês","congolesa"),
    CORREA_DO_NORTE("Coreia do Norte","norte-coreano(a)","norte-coreano","norte-coreana"),
    CORREA_DO_SUL("Coreia do Sul","sul-coreano(a)","sul-coreano","sul-coreana"),
    COSTA_DO_MARFIM("Costa do Marfim","marfinense","marfinense","marfinense"),
    COSTA_RICA("Costa Rica","costarriquenho(a)","costarriquenho","costarriquenha"),
    CROACIA("Croácia","croata","croata","croata"),
    CUBA("Cuba","cubano(a)","cubano","cubana"),
    CURACAU("Curaçau","curaçauense","curaçauense","curaçauense"),
    DINAMARCA("Dinamarca","dinamarquês(esa)","dinamarquês","dinamarquesa"),
    DJIBOUTI("Djibouti","jibutiano(a)","jibutiano","jibutiana"),
    DOMINICA("Dominica","dominiquês(esa)","dominiquo","dominiqua"),
    EGITO("Egito","egípcio(a)","egípcio","egípcia"),
    EL_SALVADOS("El Salvador","salvadorenho(a)","salvadorenho","salvadorenha"),
    EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos","emiradense","emiradense","emiradense"),
    EQUADOR("Equador","equatoriano(a)","equatoriano","equatoriana"),
    ERITREIA("Eritreia","eritreu(ia)","eritreu","eritreia"),
    ESCOCIA("Escócia","escocês(esa)","escocês","escocesa"),
    ESLOVAQUIA("Eslováquia","eslovaco(a)","eslovaco","eslovaca"),
    ESLOVENIA("Eslovênia","esloveno(a)","esloveno","eslovena"),
    ESPANHA("Espanha","espanhol(a)","espanhol","espanhola"),
    ESTADOS_FEDERADOS_DA_MICRONESIA("Estados Federados da Micronésia","micronésio(a)","micronésio","micronésia"),
    ESTADOS_UNIDOS("Estados Unidos","norte-americano(a)","norte-americano","norte-americana"),
    ESTONIA("Estónia","estoniano(a)","estoniono","estoniana"),
    ETIOPIA("Etiópia","etíope","etíope","etíope"),
    FIJI("Fiji","fijiano(a)","fijiano","fijiana"),
    FILIPINAS("Filipinas","filipino","filipino","filipino"),
    FINLANDIA("Finlândia","finlandês(esa)","finlandês","finlandesa"),
    FRANCA("França","francês(esa)","francês","francesa"),
    GABAO("Gabão","gabonês(a)","gabonês","gabonesa"),
    GAMBIA("Gâmbia","gambiano(a)","gambiano","gambiana"),
    GANA("Gana","ganês(a)","ganês","ganesa"),
    GEORGIA("Geórgia","georgiano(a)","georgiano","georgiana"),
    GRANADA("Granada","granadino(a)","granadino","granadina"),
    GRECIA("Grécia","grego(a)","grego","grega"),
    GUADALUPE("Guadalupe","guadalupense","guadalupense","guadalupense"),
    GUAM("Guam","guamês(a)","guamês","guamesa"),
    GUATEMALA("Guatemala","guatemalteco(a)","guatemalteco","guatemalteca"),
    GUIANA("Guiana","guianês(esa)","guianês","guianesa"),
    GUIANA_FRANCESA("Guiana Francesa","guianense","guianense","guianense"),
    GUINE("Guiné","guineano(a)","guineano","guineana"),
    GUINE_EQUATORIAL("Guiné Equatorial","guinéu-equatoriano(a)","guinéu-equatoriano","guinéu-equatoriana"),
    GUINE_BISSAU("Guiné-Bissau","guineense","guineense","guineense"),
    HAITI("Haiti","haitiano(a)","haitiano","haitiana"),
    HONDURAS("Honduras","hondurenho(a)","hondurenho","hondurenha"),
    HONG_KONG("Hong Kong","honconguês(esa)","honconguês","honconguesa"),
    HUNGRIA("Hungria","húngaro(a)","húngaro","húngara"),
    IEMEN("Iêmen","iemenita","iemenita","iemenita"),
    ILHAS_CAIMA("Ilhas Caimã","caimanês(a)","caimanês","caimanesa"),
    ILHAS_COOK("Ilhas Cook","cookense","cookense","cookense"),
    ILHAS_FEROE("Ilhas Feroé","faroense","faroense","faroense"),
    ILHAS_SALOMAO("Ilhas Salomão","salomonense","salomonense","salomonense"),
    ILHAS_TURCAS_E_CAICOS("Ilhas Turcas e Caicos","turquense","turquense","turquense"),
    ILHAS_VIRGENS_AMERICANAS("Ilhas Virgens Americanas","virginense","virginense","virginense"),

    //ILHAS_VIRGENS_BRITANICAS("Ilhas Virgens Britânicas","virginense","virginense","virginense"),

    INDIA("Índia","indiano(a)","indiano","indiana"),
    INDONESIA("Indonésia","indonésia(o)","indonésio","indonésia"),
    INGLATERRA("Inglaterra","inglês(esa)","inglês","inglesa"),
    IRA("Irã","iraniano(a)","iraniano","iraniana"),
    IRAQUE("Iraque","iraquiano(a)","iraquiano","iraquiana"),
    IRLANDA("Irlanda","irlandês(a)","irlandês","irlandesa"),
    IRLANDA_DO_NORTE("Irlanda do Norte","norte-irlandês(esa)","norte-irlandês","norte-irlandesa"),
    ISLANDIA("Islândia","islandês(esa)","islando","islanda"),
    ISRAEL("Israel","israelense","israelense","israelense"),
    ITALIA("Itália","italiano(a)","italiano","italiana"),
    JAMAICA("Jamaica","jamaicano(a)","jamaicano","jamaicana"),
    JAPAO("Japão","japonês(esa)","japonês","japonesa"),
    JORNDANIA("Jordânia","jordano(a)","jordano","jordana"),
    KIRIBATI("Kiribati","quiribatiano(a)","quiribatiano","quiribatiana"),
    KOSOVO("Kosovo","kosovar","kosovar","kosovar"),
    KUWAIT("Kuwait","kuwaitiano(a)","kuwaitiano","kuwaitiana"),
    LAOS("Laos","laociano(a)","laociano","laociana"),
    LESOTO("Lesoto","lesotiano(a)","lesotiano","lesotiana"),
    LRYONIA("Letônia","letã(o)","letão","letã"),
    LIBANO("Líbano","libanês(a)","libanês","libanesa"),
    LIBERIA("Libéria","liberiano(a)","liberiano","liberiana"),
    LIBIA("Líbia","líbio(a)","líbio","líbia"),
    LIECHTENSTEIN("Liechtenstein","listenstainiano(a)","listenstainiano","listenstainiana"),
    LITUANIA("Lituânia","lituano(a)","lituano","lituana"),
    LUXEMBURGO("Luxemburgo","luxemburguês(a)","luxemburguês","luxemburguesa"),
    MACAU("Macau","macaense","macaense","macaense"),
    MACEDONIA_DO_NORTE("Macedónia do Norte","macedônico(a)","macedônico","macedônica"),
    MADAGASCAR("Madagáscar","malgaxe","malgaxe","malgaxe"),
    MALASIA("Malásia","malaio(a)","malaio","malaia"),
    MALAWI("Malawi","malauiano(a)","malauiano","malauiana"),
    MALDIVAS("Maldivas","maldivo(a)","maldivo","maldiva"),
    MALI("Mali","malinês","malinês","malinês"),
    MALTA("Malta","maltês(a)","maltês","maltesa"),
    MARROCOS("Marrocos","marroquino(a)","marroquino","marroquina"),
    MARTINICA("Martinica","martinicano(a)","martinicano","martinicana"),
    MAURICIA("Maurícia","mauriciano(a)","mauriciano","mauriciana"),
    MAURITANIA("Mauritânia","mauritano(a)","mauritano","mauritana"),
    MEXICO("México","mexicano(a)","mexicano","mexicana"),
    MYANMAR("Myanmar","birmanês(a)","birmanês","birmanesa"),
    MOCAMBIQUE("Moçambique","moçambicano(a)","moçambicano","moçambicana"),
    MALDAVIA("Moldávia","moldavo(a)","moldavo","moldava"),
    MONACO("Mónaco","monegasco(a)","monegasco","monegasca"),
    MONGOLIA("Mongólia","mongol","mongol","mongol"),
    MONTENEGRO("Montenegro","montenegrino(a)","montenegrino","montenegrina"),
    MONSERROTE("Monserrate","monserratense","monserratense","monserratense"),
    NAMIBIA("Namíbia","namibiano(a)","namibiano","namibiana"),
    NAURU("Nauru","nauruano(a)","nauruano","nauruana"),
    NEPAU("Nepal","nepalês(a)","nepalês","nepalesa"),
    NICARAGUA("Nicarágua","nicaraguense","nicaraguense","nicaraguense"),

    //NIGER("Níger","nigerino(a)","nigerino","nigerina"),

    NIGERIA("Nigéria","nigeriano(a)","nigeriano","nigeriana"),
    NORUEGA("Noruega","norueguês(esa)","norueguês","norueguesa"),
    NOVA_CACEDONIA("Nova Caledônia","neocaledónio(a)","neocaledónio","neocaledónia"),
    NOVA_ZELANDIA("Nova Zelândia","neozelandês(esa)","neozelandês","neozelandesa"),
    OMA("Omã","omanense","omanense","omanense"),
    PAIS_DE_GALES("País de Gales","galês(esa)","galo","gala"),
    PAISES_BAIXOS("Países Baixos","neerlandês(a)","neerlandês","neerlandesa"),
    PALAU("Palau","palauano(a)","palauano","palauana"),
    PALESTINA("Palestina","palestiniano(a)","palestiniano","palestiniana"),
    PANAMA("Panamá","panamenho(a)","panamenho","panamenha"),
    PAPUA_NOVA_GUINE("Papua-Nova Guiné","papua","papua","papua"),
    PAQUISTAO("Paquistão","paquistanês(a)","paquistanês","paquistanesa"),
    PARAGUAI("Paraguai","paraguaio(a)","paraguaio","paraguaia"),
    PERU("Peru","peruano(a)","peruano","peruana"),
    POLINESIA_FRANCESA("Polinésia Francesa","polinésio(a)","polinésio","polinésia"),
    POLONIA("Polónia","polaco(a)","polaco","polaca"),
    PORTO_RICO("Porto Rico","porto-riquenho(a)","porto-riquenho","porto-riquenha"),
    PORTUGAL("Portugal","português(esa)","português","portuguesa"),
    QUENIA("Quênia","queniano(a)","queniano","queniana"),
    QUIRQUISTAO("Quirguistão","quirguiz","quirguiz","quirguiz"),
    REINO_DE_ESSUATINI("Reimpo de Essuatíni","essuatiniano(a)","essuatinianO","essuatiniana"),
    REINO_UNIDO("Reino Unido","britânico(a)","britânico","britânica"),
    REPUBLICA_CENTRO_AFRICANA("República Centro-Africana","centro-africano(a)","centro-africano","centro-africana"),
    REPUBLICA_CHECA("República Checa","tcheco(a)","tcheco","tcheca"),
    REPUBLICA_DEMOCRATICA_DO_CONGO("República Democrática do Congo","congolês(a)","congolês","congolesa"),
    REPUBLICA_DOMINICANA("República Dominicana","dominicano(a)","dominicano","dominicana"),
    ROMENIA("Roménia","romeno(a)","romeno","romena"),
    RUANDA("Ruanda","ruandês(a)","ruandês","ruandesa"),
    RUSSIA("Rússia","russo(a)","russo","russa"),
    SAO_MARTINHO("São Martinho","são-martinhense","são-martinhense","são-martinhense"),
    SAMOA("Samoa","samoano(a)","samoano","samoana"),
    SAMOA_AMERICANA("Samoa Americana","samoense","samoense","samoense"),
    SANTA_LUCIA("Santa Lúcia","santa-luciense","santa-luciense","santa-luciense"),
    SAO_CRISTOVAO_E_NEVES("São Cristóvão e Neves","são-cristovense","são-cristovense","são-cristovense"),
    SAN_MARINO("San Marino","são-marinhense","são-marinhense","são-marinhense"),
    SAO_TOMR_E_PRINCIPE("São Tomé e Príncipe","são-tomense","são-tomense","são-tomense"),
    SAO_VICENTE_E_GANADINAS("São Vicente e Granadinas","são-vicentino(a)","são-vicentino","são-vicentina"),
    SENEGAL("Senegal","senegalês(esa)","senegalês","senegalesa"),
    SERRA_LEOA("Serra Leoa","serra-leonês(a)","serra-leonês","serra-leonesa"),
    SERVIA("Sérvia","sérvio(a)","sérvio","sérvia"),
    SEICHELES("Seicheles","seichelense","seichelense","seichelense"),
    SINGAPURA("Singapura","singapurense","singapurense","singapurense"),
    SIRIA("Síria", "sírio(a)","sírio","síria"),
    SOMALIA("Somália","somali","somali","somali"),
    SRI_LANKA("Sri Lanka","cingalês(a)","cingalês","cingalesa"),
    SUDAO("Sudão","sudanês(a)","sudanês","sudanesa"),
    SUECIA("Suécia","sueco(a)","sueco","sueca"),
    SUICA("Suíça","suíço(a)","suíço","suíça"),
    SURINAME("Suriname","surinamês(a)","surinamês","surinamesa"),
    TAIWAN("Taiwan","taiwanês(a)","taiwanês","taiwanesa"),
    TAJIQUISTAO("Tajiquistão","tajique","tajique","tajique"),
    TAILANDIA("Tailândia","tailandês","tailandês","tailandês"),
    TAIPE_CHINESA("Taipé Chinesa","taiwanês(a)","taiwanês","taiwanesa"),
    TANZANIA("Tanzânia","tanzaniano(a)","tanzaniano","tanzaniana"),
    TIMOR_LESTE("Timor-Leste","timorense","timorense","timorense"),
    TOGO("Togo","togolês(a)","togolês","togolesa"),
    TONGA("Tonga","tonganês(esa)","tonganês","tonganesa"),
    TRINIDAD_E_TOBAGO("Trinidad e Tobago","trinitário(a)-tobagense","trinitário-tobagense","trinitária-tobagense"),
    TUNISIA("Tunísia","tunisiano(a)","tunisiano","tunisiana"),
    TURQUEMENISTAO("Turquemenistão","turquemeno(a)","turquemeno","turquemena"),
    TURQUIA("Turquia","turco(a)","turco","turca"),
    TUVALU("Tuvalu","tuvaluano(a)","tuvaluano","tuvaluana"),
    UCRANIA("Ucrânia","ucraniano(a)","ucraniano","ucraniana"),
    UGANDA("Uganda","ugandense","ugandense","ugandense"),
    URUGUAI("Uruguai","uruguaio(a)","uruguaio","uruguaia"),
    UZBEQUISTAO("Uzbequistão","usbeque","usbeque","usbeque"),
    VANUATU("Vanuatu","vanuatuense","vanuatuense", "vanuatuense"),
    VATICANO("Vaticano","vaticano(a)", "vaticano","vaticana"),
    VENEZUELA("Venezuela","venezuelano(a)","venezuelano","venezuelana"),
    VIETNA("Vietnã","vietnamita","vietnamita","vietnamita"),
    ZAMBIA("Zâmbia","zambiano(a)","zambiano","zambiana"),
    ZIMBABWE("Zimbabwe","zimbabuano(a)","zimbabuano","zimbabuana");

    private final String pais;
    private final String nacionalidade;
    private final String masculino;
    private final String feminino;

    Nacionalidade(final String pais, final String nacionalidade, final String masculino, final String feminino){
        this.pais = pais;
        this.nacionalidade = nacionalidade;
        this.masculino = masculino;
        this.feminino = feminino;
    }

    public String getPais() {
        return this.pais;
    }

    public String getNacionalidade() {
        return this.nacionalidade;
    }

    public String getMasculino() {
        return this.masculino;
    }

    public String getFeminino() {
        return this.feminino;
    }

    @Override
    public String toString() {
        return pais;
    }
}
